[package]
name = "tape_drive"
version = "0.1.0"
authors = ["cannero"]
edition = "2018"

[dependencies]
surf = "2.0.0-alpha.2"
serde = { version = "1.0.106", features = ["derive"] }
pulldown-cmark = "0.7.0"
nom = "6.0.0-alpha1"

[dependencies.async-std]
version = "1.5.0"
features = ["attributes"]