use std::fs::File;
use std::io::prelude::*;
use tape_drive::nom_parser;

#[test]
fn parse_file_test() {
    let mut file = File::open("files/README.md").unwrap();
    let mut contents = String::new();
    file.read_to_string(&mut contents).unwrap();
    let streamers = nom_parser::parse_file(&contents).unwrap();
    let streamer_names = vec![
        "Adam13531",
        "Adron Hall",
        "Al Sweigart",
        "Albérico Dias Barreto Filho",
        "Alexander Simovic",
        "Amorelandra",
        "Andrew Kelley",
        "Andy Li",
        "Anthony Sottile",
        "Antonio Maiorano",
        "Anton Kuzmenko",
        "Ardalis - Steve Smith",
        "Armin Ronacher",
        "Baggers",
        "BarRaider",
        "Beachcasts",
        "Ben Greenier",
        "Benjamin Lannon",
        "Bobby Johnson",
        "Brandon Satrom",
        "Brent Schooley (Chef Brent)",
        "Brian Clark (Clarkio)",
        "Brian Lagunas",
        "Brian McKenna",
        "britocoding",
        "Brookzerker",
        "Btor",
        "Caidan Williams",
        "Cailir",
        "CaptainKraft",
        "Casey Muratori",
        "Catalin Miron",
        "ChaelCodes",
        "Chiroptical",
        "Codebase Alpha (Essenbee)",
        "Codephobia",
        "CodeRushed (Mark Miller)",
        "Código Falado",
        "Collin Henderson",
        "Corey Weathers",
        "Cory knox",
        "Daniel Jenkins",
        "Daniel Reis",
        "Daniel Stenberg",
        "Darko Meszaros",
        "David Pedersen",
        "David Poindexter (roberttables)",
        "DevChatter",
        "Developers Garage",
        "Dillon Pentz (DillonEA)",
        "Dmitry Figol",
        "DrunkDevs",
        "Emanuele Bartolesi",
        "Eser Ozvataf",
        "Feross Aboukhadijeh",
        "Ferris",
        "Fletcher (IAmFletcher)",
        "Frank Boucher",
        "Franziska Hinkelmann",
        "Freya Holmér",
        "Gareth Hubball",
        "Gary Ewan Park",
        "Gary Hockin",
        "Gary Kramlich",
        "Gavin Barron",
        "Geoffrey Huntley",
        "Go_Maestro_Go",
        "Gwen Frey",
        "HardlyDifficult",
        "Holden Karau",
        "HowToCodeWell (Peter Fisher)",
        "Ian Lovett",
        "iDevelopThings",
        "Jack Mott",
        "Jason Lengstorf",
        "Jeff Fritz",
        "Jeff Lindsay",
        "Jeff Panici",
        "Jen Tong",
        "Jesse Skinner",
        "Jessica Mak",
        "Jochen Lillich",
        "Joe Bew",
        "Jon Gjengset",
        "Jonatas \"Jojo\" Baldin",
        "Jonathan Blow",
        "Jorge Cano",
        "Josh Hawkins",
        "Josh Kupka",
        "Josh Justice",
        "KalleHallden",
        "KensoDev",
        "Kent C. Dodds",
        "Keraf",
        "Kevin Griffin",
        "KeyFramers",
        "Krzysztof 'Chris' Cieslak",
        "Kyle Shevlin",
        "Layla Porter",
        "Leomendesm",
        "Liz Phillips (Illuminated Space)",
        "Marco Bruno",
        "Mark Kraus",
        "Mark Mandel",
        "Marko Pavlovic",
        "Matt Groves",
        "Matt Layman",
        "Matt Podwysocki",
        "Mattias Petter Johansson",
        "MechJack",
        "Micah Elizabeth Scott (scanlime)",
        "Michael Jolley (BaldBeardedBuilder)",
        "Mike Conley",
        "Nicholas Brochu",
        "Nick Busey",
        "Nicolai Parlog",
        "Ninjabunny9000",
        "nmarulo",
        "nullpointer128",
        "Pavithra Kodmad",
        "Per Vognsen",
        "Phil Nash",
        "PixelogicDev",
        "Rachael Tatman",
        "RadicalFishGames",
        "Ragnar Thor",
        "Randall Hunt",
        "Ricardo Tavares",
        "Robin Pokorny",
        "Rúben Gomes",
        "Russell Hay",
        "RyanWarnerCodes",
        "Sch3lpSC2",
        "Sean Larkin",
        "Sébastien Rancoud",
        "Sebastian Krzyżanowski",
        "Sergio Cinos",
        "Shinmera",
        "Shirley Wu",
        "Simeon Vincent",
        "Sir Lynix Van Frietjes",
        "Siva",
        "Sorskoot",
        "Stan Daniels-Roth",
        "Suz Hinton",
        "Swizec Teller",
        "Syanoks",
        "Tae'lur Alexis",
        "Talk2MeGooseman (Erik Guzman)",
        "Ted M. Young",
        "ThePrimeagen",
        "Thomas Soerensen",
        "Thorsten Lorenz",
        "Tierney Cyren",
        "Tim Ermilov",
        "Trezy",
        "Tsoding",
        "TutorExilius",
        "Tyler Leonhardt",
        "Vogue and Code (April Speight)",
        "WindybeardGames",
        "Yosh",
        "Zorchenhimer",
        "Michael Crump",
        "Michael Henderson (robedcoder / leadcoder)",
    ];
    //println!("{:?}", streamers);
    for name in streamer_names {
        assert!(streamers.iter().any(|s| s.name() == &name), name);
    }

    assert_eq!(streamers.len(), 180 - 15);
}
